#!/usr/bin/env bash
# This Bash script transfers a file from our client to a server using scp

usage() {
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
}

if [ "$#" -lt 4 ]; then
  usage
fi

FILE_PATH=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$IP:~/"
