#!/usr/bin/env bash

# Usage function to display usage message
usage() {
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
}

# Check if less than 4 parameters passed
if [ "$#" -lt 4 ]; then
  usage
fi

FILE_PATH=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# Use scp to transfer file to the user's home directory, disabling strict host key checking
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$IP:~/"
