#!/usr/bin/env bash
#servers are the pieces of software generating and serving HTML pages
#install Nginx and configure a custom HTML page

apt-get update -y
apt-get install nginx -y 
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Holberton School" > /var/www/html/index.html'
service nginx restart
